# Generated by Django 2.0.2 on 2018-04-08 00:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('favoriteID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='retweet',
            fields=[
                ('retweetID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('tweetID', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(max_length=140)),
                ('PostTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='twitteruser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='posterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.twitteruser'),
        ),
        migrations.AddField(
            model_name='retweet',
            name='tweetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.tweet'),
        ),
        migrations.AddField(
            model_name='retweet',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.twitteruser'),
        ),
        migrations.AddField(
            model_name='follower',
            name='followerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_name', to='interface.twitteruser'),
        ),
        migrations.AddField(
            model_name='follower',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='interface.twitteruser'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='tweetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.tweet'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.twitteruser'),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('userID', 'followerID')},
        ),
    ]
