# Generated by Django 2.0.2 on 2018-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='password',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='username',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
