# Generated by Django 2.0.2 on 2018-04-11 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='LastName',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.twitteruser'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='followerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_name', to='interface.twitteruser'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='interface.twitteruser'),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.twitteruser'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='posterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.twitteruser'),
        ),
    ]
