# Generated by Django 2.0.2 on 2018-04-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20180408_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='userID',
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='username',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
