# Generated by Django 2.0.2 on 2018-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20180408_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='username',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
