# Generated by Django 2.0.2 on 2018-04-09 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20180408_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='tweetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interface.tweet'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interface.twitteruser'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='followerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follower_name', to='interface.twitteruser'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_name', to='interface.twitteruser'),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='tweetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interface.tweet'),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interface.twitteruser'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='posterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interface.twitteruser'),
        ),
    ]
